// This file was generated by the tool gen.

#ifndef _GEOMETRY_MSGS_QUATERNION_H_
#define _GEOMETRY_MSGS_QUATERNION_H_

#include "../topic.hpp"

// Manualy include list

namespace geometry_msgs
{

class Quaternion: public ros2::Topic<Quaternion>
{
public:
    using SharedPtr = std::shared_ptr<Quaternion>;

    double x;
    double y;
    double z;
    double w;

    Quaternion()
        : Topic("geometry_msgs::msg::dds_::Quaternion_", "Quaternion", GEOMETRY_MSGS_QUATERNION_ID),
        x(0),
        y(0),
        z(0),
        w(0)
    {
    }

    bool serialize(void* msg_buf, Quaternion* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_double(writer, topic->x);
        (void) ucdr_serialize_double(writer, topic->y);
        (void) ucdr_serialize_double(writer, topic->z);
        (void) ucdr_serialize_double(writer, topic->w);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Quaternion* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_double(reader, &topic->x);
        (void) ucdr_deserialize_double(reader, &topic->y);
        (void) ucdr_deserialize_double(reader, &topic->z);
        (void) ucdr_deserialize_double(reader, &topic->w);

        return !reader->error;
    }

    uint32_t size_of_topic(const Quaternion* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 8) + 8;
        size += ucdr_alignment(size, 8) + 8;
        size += ucdr_alignment(size, 8) + 8;
        size += ucdr_alignment(size, 8) + 8;

        return size - previousSize;
    }

};

} // namespace geometry_msgs

#endif // _GEOMETRY_MSGS_QUATERNION_H_