// This file was generated by the tool gen.

#ifndef _RCL_INTERFACES_PARAMETEREVENT_H_
#define _RCL_INTERFACES_PARAMETEREVENT_H_

#include "../topic.hpp"

// Manualy include list
// builtin_interfaces::Time
// suggest
#include "builtin_interfaces/Time.hpp"
// rcl_interfaces::Parameter
// suggest
#include "rcl_interfaces/Parameter.hpp"

namespace rcl_interfaces
{

class ParameterEvent: public ros2::Topic<ParameterEvent>
{
public:
    using SharedPtr = std::shared_ptr<ParameterEvent>;

    builtin_interfaces::Time stamp;
    std::string node;
    std::vector<rcl_interfaces::Parameter> new_parameters;
    std::vector<rcl_interfaces::Parameter> changed_parameters;
    std::vector<rcl_interfaces::Parameter> deleted_parameters;

    ParameterEvent()
        : Topic("rcl_interfaces::msg::dds_::ParameterEvent_", "ParameterEvent", RCL_INTERFACES_PARAMETEREVENT_ID)
    {
    }

    bool serialize(void* msg_buf, ParameterEvent* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) stamp.serialize(writer, &topic->stamp);
        (void) ucdr_serialize_string(writer, topic->node.data());
        for(size_t i = 0; i < topic->new_parameters.size(); i++)
        {
            (void) new_parameters[i].serialize(writer, &topic->new_parameters[i]);
        }
        for(size_t i = 0; i < topic->changed_parameters.size(); i++)
        {
            (void) changed_parameters[i].serialize(writer, &topic->changed_parameters[i]);
        }
        for(size_t i = 0; i < topic->deleted_parameters.size(); i++)
        {
            (void) deleted_parameters[i].serialize(writer, &topic->deleted_parameters[i]);
        }

        return !writer->error;
    }

    bool deserialize(void* msg_buf, ParameterEvent* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) stamp.deserialize(reader, &topic->stamp);
        (void) ucdr_deserialize_string(reader, topic->node.data(), topic->node.capacity());
        for(size_t i = 0; i < topic->new_parameters.size(); i++)
        {
            (void) new_parameters[i].deserialize(reader, &topic->new_parameters[i]);
        }
        for(size_t i = 0; i < topic->changed_parameters.size(); i++)
        {
            (void) changed_parameters[i].deserialize(reader, &topic->changed_parameters[i]);
        }
        for(size_t i = 0; i < topic->deleted_parameters.size(); i++)
        {
            (void) deleted_parameters[i].deserialize(reader, &topic->deleted_parameters[i]);
        }

        return !reader->error;
    }

    uint32_t size_of_topic(const ParameterEvent* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += stamp.size_of_topic(&topic->stamp, size);
        size += ucdr_alignment(size, 4) + 4 + (uint32_t)(topic->node.length() + 1);
        for(size_t i = 0; i < topic->new_parameters.size(); i++)
        {
            size += new_parameters[i].size_of_topic(&topic->new_parameters[i], size);
        }
        for(size_t i = 0; i < topic->changed_parameters.size(); i++)
        {
            size += changed_parameters[i].size_of_topic(&topic->changed_parameters[i], size);
        }
        for(size_t i = 0; i < topic->deleted_parameters.size(); i++)
        {
            size += deleted_parameters[i].size_of_topic(&topic->deleted_parameters[i], size);
        }

        return size - previousSize;
    }

};

} // namespace rcl_interfaces

#endif // _RCL_INTERFACES_PARAMETEREVENT_H_