// This file was generated by the tool gen.

#ifndef _RCL_INTERFACES_SETPARAMETERSRESULT_H_
#define _RCL_INTERFACES_SETPARAMETERSRESULT_H_

#include "../topic.hpp"

// Manualy include list

namespace rcl_interfaces
{

class SetParametersResult: public ros2::Topic<SetParametersResult>
{
public:
    using SharedPtr = std::shared_ptr<SetParametersResult>;

    bool successful;
    std::string reason;

    SetParametersResult()
        : Topic("rcl_interfaces::msg::dds_::SetParametersResult_", "SetParametersResult", RCL_INTERFACES_SETPARAMETERSRESULT_ID),
        successful(false)
    {
    }

    bool serialize(void* msg_buf, SetParametersResult* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_bool(writer, topic->successful);
        (void) ucdr_serialize_string(writer, topic->reason);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, SetParametersResult* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_bool(reader, &topic->successful);
        (void) ucdr_deserialize_string(reader, topic->reason);

        return !reader->error;
    }

    uint32_t size_of_topic(const SetParametersResult* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 1) + 1;
        size += ucdr_alignment(size, 4) + 4 + (uint32_t)(topic->reason.length());

        return size - previousSize;
    }

};

} // namespace rcl_interfaces

#endif // _RCL_INTERFACES_SETPARAMETERSRESULT_H_