// This file was generated by the tool gen.

#ifndef _STD_MSGS_BOOL_H_
#define _STD_MSGS_BOOL_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class Bool: public ros2::Topic<Bool>
{
public:
    using SharedPtr = std::shared_ptr<Bool>;

    bool data;

    Bool()
        : Topic("std_msgs::msg::dds_::Bool_", "Bool", STD_MSGS_BOOL_ID),
        data(false)
    {
    }

    bool serialize(void* msg_buf, Bool* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_bool(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Bool* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_bool(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const Bool* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 1) + 1;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_BOOL_H_