// This file was generated by the tool gen.

#ifndef _STD_MSGS_EMPTY_H_
#define _STD_MSGS_EMPTY_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class Empty: public ros2::Topic<Empty>
{
public:
    using SharedPtr = std::shared_ptr<Empty>;

    uint8_t structure_needs_at_least_one_member;

    Empty()
        : Topic("std_msgs::msg::dds_::Empty_", "Empty", STD_MSGS_EMPTY_ID),
        structure_needs_at_least_one_member(0)
    {
    }

    bool serialize(void* msg_buf, Empty* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_uint8_t(writer, topic->structure_needs_at_least_one_member);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Empty* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_uint8_t(reader, &topic->structure_needs_at_least_one_member);

        return !reader->error;
    }

    uint32_t size_of_topic(const Empty* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 1) + 1;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_EMPTY_H_