// This file was generated by the tool gen.

#ifndef _STD_MSGS_FLOAT64_H_
#define _STD_MSGS_FLOAT64_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class Float64: public ros2::Topic<Float64>
{
public:
    using SharedPtr = std::shared_ptr<Float64>;

    double data;

    Float64()
        : Topic("std_msgs::msg::dds_::Float64_", "Float64", STD_MSGS_FLOAT64_ID),
        data(0)
    {
    }

    bool serialize(void* msg_buf, Float64* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_double(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Float64* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_double(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const Float64* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 8) + 8;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_FLOAT64_H_