// This file was generated by the tool gen.

#ifndef _STD_MSGS_FLOAT32_H_
#define _STD_MSGS_FLOAT32_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class Float32: public ros2::Topic<Float32>
{
public:
    using SharedPtr = std::shared_ptr<Float32>;

    float data;

    Float32()
        : Topic("std_msgs::msg::dds_::Float32_", "Float32", STD_MSGS_FLOAT32_ID),
        data(0)
    {
    }

    bool serialize(void* msg_buf, Float32* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_float(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Float32* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_float(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const Float32* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_FLOAT32_H_