// This file was generated by the tool gen.

#ifndef _STD_MSGS_INT16_H_
#define _STD_MSGS_INT16_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class Int16: public ros2::Topic<Int16>
{
public:
    using SharedPtr = std::shared_ptr<Int16>;

    int16_t data;

    Int16()
        : Topic("std_msgs::msg::dds_::Int16_", "Int16", STD_MSGS_INT16_ID),
        data(0)
    {
    }

    bool serialize(void* msg_buf, Int16* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_int16_t(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Int16* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_int16_t(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const Int16* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 2) + 2;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_INT16_H_