// This file was generated by the tool gen.

#ifndef _STD_MSGS_INT32_H_
#define _STD_MSGS_INT32_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class Int32: public ros2::Topic<Int32>
{
public:
    using SharedPtr = std::shared_ptr<Int32>;

    int32_t data;

    Int32()
        : Topic("std_msgs::msg::dds_::Int32_", "Int32", STD_MSGS_INT32_ID),
        data(0)
    {
    }

    bool serialize(void* msg_buf, Int32* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_int32_t(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, Int32* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_int32_t(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const Int32* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_INT32_H_