// This file was generated by the tool gen.

#ifndef _STD_MSGS_UINT16_H_
#define _STD_MSGS_UINT16_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class UInt16: public ros2::Topic<UInt16>
{
public:
    using SharedPtr = std::shared_ptr<UInt16>;

    uint16_t data;

    UInt16()
        : Topic("std_msgs::msg::dds_::UInt16_", "UInt16", STD_MSGS_UINT16_ID),
        data(0)
    {
    }

    bool serialize(void* msg_buf, UInt16* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_uint16_t(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, UInt16* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_uint16_t(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const UInt16* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 2) + 2;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_UINT16_H_