// This file was generated by the tool gen.

#ifndef _STD_MSGS_UINT64MULTIARRAY_H_
#define _STD_MSGS_UINT64MULTIARRAY_H_

#include "../topic.hpp"

// Manualy include list
// std_msgs::MultiArrayLayout
// suggest
#include "std_msgs/MultiArrayLayout.hpp"

namespace std_msgs
{

class UInt64MultiArray: public ros2::Topic<UInt64MultiArray>
{
public:
    using SharedPtr = std::shared_ptr<UInt64MultiArray>;

    std_msgs::MultiArrayLayout layout;
    std::vector<uint64_t> data;

    UInt64MultiArray()
        : Topic("std_msgs::msg::dds_::UInt64MultiArray_", "UInt64MultiArray", STD_MSGS_UINT64MULTIARRAY_ID)
    {
    }

    bool serialize(void* msg_buf, UInt64MultiArray* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) layout.serialize(writer, &topic->layout);
        (void) ucdr_serialize_vec_uint64_t(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, UInt64MultiArray* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) layout.deserialize(reader, &topic->layout);
        (void) ucdr_deserialize_vec_uint64_t(reader, topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const UInt64MultiArray* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += layout.size_of_topic(&topic->layout, size);
        size += ucdr_alignment(size, 4) + 4;
        size += ucdr_alignment(size, 8) + (topic->data.size() * 8);

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_UINT64MULTIARRAY_H_