// This file was generated by the tool gen.

#ifndef _STD_MSGS_UINT32_H_
#define _STD_MSGS_UINT32_H_

#include "../topic.hpp"

// Manualy include list

namespace std_msgs
{

class UInt32: public ros2::Topic<UInt32>
{
public:
    using SharedPtr = std::shared_ptr<UInt32>;

    uint32_t data;

    UInt32()
        : Topic("std_msgs::msg::dds_::UInt32_", "UInt32", STD_MSGS_UINT32_ID),
        data(0)
    {
    }

    bool serialize(void* msg_buf, UInt32* topic)
    {
        ucdrBuffer* writer = (ucdrBuffer*)msg_buf;
        (void) ucdr_serialize_uint32_t(writer, topic->data);

        return !writer->error;
    }

    bool deserialize(void* msg_buf, UInt32* topic)
    {
        ucdrBuffer* reader = (ucdrBuffer*)msg_buf;
        (void) ucdr_deserialize_uint32_t(reader, &topic->data);

        return !reader->error;
    }

    uint32_t size_of_topic(const UInt32* topic, uint32_t size)
    {
        (void) (topic);

        uint32_t previousSize = size;
        size += ucdr_alignment(size, 4) + 4;

        return size - previousSize;
    }

};

} // namespace std_msgs

#endif // _STD_MSGS_UINT32_H_